package com.softzone.stoner.purchasements;

import javax.swing.CellEditor;

public class addInvoiceWindow extends javax.swing.JFrame {

    public addInvoiceWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {


        jFrame1 = new javax.swing.JFrame();
        Lowerpanel = new javax.swing.JPanel();
        jScrollPane = new javax.swing.JScrollPane();
        invoiceTable = new javax.swing.JTable();
        supLabel = new javax.swing.JLabel();
        supNameText = new javax.swing.JTextField();
        invoiceIdLabel = new javax.swing.JLabel();
        invoiceIdText = new javax.swing.JTextField();
        SaveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        addSupButton = new javax.swing.JButton();
        setAmountsButton=new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        newMenuItem = new javax.swing.JMenu();
        saveMenuItem = new javax.swing.JMenu();
        editMenu = new javax.swing.JMenu();
        handler = new InvoiceHandler();



        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
                jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 400, Short.MAX_VALUE));
        jFrame1Layout.setVerticalGroup(
                jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 300, Short.MAX_VALUE));




 
        setTitle("Add invoice");

        invoiceTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
                },
                new String[]{
                    "Item", "Qty", "Unit prize", "Amount"
                }));
        jScrollPane.setViewportView(invoiceTable);

        supLabel.setText("Supplier : ");
        invoiceIdLabel.setText("Invoice ID : ");

        supNameText.setText("jTextField2");
        supNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supNameTextActionPerformed(evt);
            }
        });

        addSupButton.setText("Add new supplier");
        addSupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSupButtonActionPerformed(evt);
            }
        });

        invoiceTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EnterKeyPressed(evt);
            }
        });

        SaveButton.setText("Save");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);


            }
        });
        setAmountsButton.setText("Calculate Amounts");
        setAmountsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setAmountsButtonActionPerformed(evt);


            }
        });


        javax.swing.GroupLayout LowerpanelLayout = new javax.swing.GroupLayout(Lowerpanel);
        Lowerpanel.setLayout(LowerpanelLayout);
        LowerpanelLayout.setHorizontalGroup(
                LowerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LowerpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(supLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(supNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addSupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(invoiceIdLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(invoiceIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addContainerGap())
                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LowerpanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(setAmountsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap()));
        LowerpanelLayout.setVerticalGroup(
                LowerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LowerpanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(LowerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(supLabel)
                .addComponent(supNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(addSupButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(invoiceIdLabel)
                .addComponent(invoiceIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                )
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(LowerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(setAmountsButton)
                .addComponent(SaveButton)
                .addComponent(cancelButton))
                .addContainerGap()));

        fileMenu.setText("File");

        newMenuItem.setText("New");
        fileMenu.add(newMenuItem);

        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        menuBar.add(fileMenu);

        editMenu.setText("Edit");
        menuBar.add(editMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Lowerpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Lowerpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE));

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>

    private void supNameTextActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        
    }

    private void addSupButtonActionPerformed(java.awt.event.ActionEvent evt) {
       
        //open with singleton pattern 
        addSupplierWindow.getUniqueAddSupWindow().setVisible(true);
    }

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {
      
        //send data to handler
        handler.setSupplier(supNameText.getText());
        handler.setInvoiceID(invoiceIdText.getText());
        handler.setTable(invoiceTable);
        
    }

    //validate items
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {
        //***** update: delete value in selected cell
        
        //clear text field
        supNameText.setText("");
        //clear table
        for (int i = 0; i < invoiceTable.getRowCount(); i++) {
            for (int j = 0; j < invoiceTable.getColumnCount(); j++) {
                invoiceTable.setValueAt(null, i, j);
            }
        }


    }
    
    private void setAmountsButtonActionPerformed(java.awt.event.ActionEvent evt) {
        //***** update: delete value in selected cell
        //clear text field
        supNameText.setText("");
        //clear table
        for (int i = 0; i < invoiceTable.getRowCount(); i++) {            
            for (int j = 0; j < invoiceTable.getColumnCount(); j++) {
                if(j==3){
                    String qty=(String)invoiceTable.getValueAt(i, 1);
                    String unitPrize=(String)invoiceTable.getValueAt(i, 2);
                    int unitP=Integer.parseInt(unitPrize);
                    int qtyInt=Integer.parseInt(qty);
                    invoiceTable.setValueAt(qtyInt*unitP, i, j);
                }
                
            }
        }


    }
    
    private void EnterKeyPressed(java.awt.event.KeyEvent evt) {
        if (evt.getKeyCode() == evt.VK_ENTER)
        {
           CellEditor editor = invoiceTable.getCellEditor();
        }
    }

    /**
     * @param args the command line arguments
     */
  
    // Variables declaration - do not modify
    private javax.swing.JPanel Lowerpanel;
    private javax.swing.JButton SaveButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton addSupButton;
    private javax.swing.JButton setAmountsButton;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JTable invoiceTable;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu newMenuItem;
    private javax.swing.JMenu saveMenuItem;
    private javax.swing.JLabel supLabel;
    private javax.swing.JTextField supNameText;
    private javax.swing.JLabel invoiceIdLabel;
    private javax.swing.JTextField invoiceIdText;
    private InvoiceHandler handler;
    // End of variables declaration
}
